server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7002/eureka/
  instance:
    # 加入后，访问eureka web ui可以将服务地址从服务名：ip更换为instance-id
    instance-id: payment8001
    # 访问路径显示ip地址
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.i61.SpringCloud.entities
